version: '3.9'
services:
  nestjs-app:
    image: flowcommerce-app:latest
    ports:
      - "3001:3000"
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:dev
    env_file:
      - .env
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_URL=amqp://${RABBITMQ_USER}:${RABBITMQ_PASS}@${RABBITMQ_HOST}:${RABBITMQ_PORT}

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672" # default port
      - "15672:15672" # web management default port
    env_file:
      - .env
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASS}

  stock_worker:
    image: flowcommerce-stock:latest
    env_file:
      - .env
    command: npm run start:worker:stock
    depends_on:
      - rabbitmq
    deploy:
      replicas: 1

  payment_worker:
    image: flowcommerce-payment:latest
    env_file:
      - .env
    command: npm run start:worker:payment
    depends_on:
      - rabbitmq
    deploy:
      replicas: 1
