version: '3.9'
services:
  nestjs-app:
    image: flowcommerce-app:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:dev
    env_file:
      - .env
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_URL=amqp://${RABBITMQ_USER}:${RABBITMQ_PASS}@${RABBITMQ_HOST}:${RABBITMQ_PORT}

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672" # default port
      - "15672:15672" # web management default port
    env_file:
      - .env
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASS}

  stock_worker_1:
    image: flowcommerce-stock:latest
    build:
      context: .
      dockerfile: Dockerfile.stock.worker
    env_file:
      - .env
    command: npm run start:worker:stock:prod
    depends_on:
      - rabbitmq

  stock_worker_2:
    image: flowcommerce-stock:latest
    build:
      context: .
      dockerfile: Dockerfile.stock.worker
    env_file:
      - .env
    command: npm run start:worker:stock:prod
    depends_on:
      - rabbitmq

  payment_worker_1:
    image: flowcommerce-payment:latest
    build:
      context: .
      dockerfile: Dockerfile.payment.worker
    env_file:
      - .env
    command: npm run start:worker:payment:prod
    depends_on:
      - rabbitmq

  payment_worker_2:
    image: flowcommerce-payment:latest
    build:
      context: .
      dockerfile: Dockerfile.payment.worker
    env_file:
      - .env
    command: npm run start:worker:payment:prod
    depends_on:
      - rabbitmq